#!/nfs/sw/R/R-4.0.0/bin/Rscript
################################################################################
### COPYRIGHT ##################################################################

# New York Genome Center

# SOFTWARE COPYRIGHT NOTICE AGREEMENT
# This software and its documentation are copyright (2023) by the New York
# Genome Center. All rights are reserved. This software is supplied without
# any warranty or guaranteed support whatsoever. The New York Genome Center
# cannot be responsible for its use, misuse, or functionality.

# Author: William F. Hooper

################################################################# /COPYRIGHT ###
################################################################################
## Compute ratio of tumor depth to normal depth as generated by fragCounter
libs = c('optparse', 'GenomicRanges')
invisible(suppressPackageStartupMessages(sapply(libs, require, character.only=T)))
options(width=200, scipen=999)


## Get arguments
option_list = list( 
    make_option(c("-t", "--tumor"),   type='character', help="Tumor coverage RDS file as generated by fragCounter"),
    make_option(c("-n", "--normal"),  type='character', help="Normal coverage RDS file as generated by fragCounter"),
    make_option(c("-g", "--gender"),  type='character', help="Sample gender for X-specific processing (male/female)"),
    make_option(c("-o", "--outfile"), type='character', help="Output file"))
opt = parse_args(OptionParser(option_list=option_list))


## Read coverage objects
tumor = readRDS(opt$tumor)
normal = readRDS(opt$normal)

## Make sure all bins are the same
if (!all(seqnames(tumor) == seqnames(normal))) stop("seqnames don't align!")
if (!all(start(tumor) == start(normal))) stop("bin starts don't align!")
if (!all(end(tumor) == end(normal))) stop("bin ends don't align!")

## Divide tumor bins by normal bins
## Treat all 0/0 as 0: as per Xiaotong Yao's advice
## Make sure we're using the correct chr style
tumor$ratio = tumor$reads.corrected / normal$reads.corrected
tumor$ratio[tumor$reads.corrected == 0 & normal$reads.corrected == 0] = 0 
seqlevelsStyle(tumor) = 'UCSC'


## Cast to data frame
tumor.df = as.data.frame(tumor)[c('seqnames','start','end','width','strand','ratio')]

## Write to disk in csv and rds format
outfile.rds = gsub('\\.csv$','.rds', opt$outfile)
write.csv(tumor.df, opt$outfile, row.names=F, quote=F)
saveRDS(tumor, outfile.rds)
